package br.edu.cefsa.EC6.Compiladores.N1B1.Dojo;

public enum Tipo {
	VARIAVEL, 
	PALAVRARESERVADA, 
	OPERADOR, 
	METODO, 
	FUNCAO, 
	OBJETO,
	BOOLEAN, BYTE, CHAR, DOUBLE, FLOAT, INT, LONG, SHORT, STRING;
}
